import React from 'react'


// Page used to show result of QR scan.
// This is essentially what the TSA agents would see.
// Assume that this code scan is generated by 

function QRRedirect() {
  return (
    <div>
      {/* Name */}
      {/* Passport */}
      {/* Passport Nationality */}
      {/* COVID Records */}
    </div>
  )
}

export default QRRedirect
